version: '3.1'
services:
  postgresqldb:
    image: postgis
    build: ./data_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=peakdb
      - POSTGRES_USER=peakdb
      - POSTGRES_DB=peakdb
  app:
      container_name:  mountainpeaks-postgis
      image:  mountainpeaks-postgis
      build: ./
      ports:
        - "8081:8081"
      depends_on:
        - postgresqldb
  
    