version: '3.1'
services:
  peakdb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=peakdb
    networks:
     - mountainPeakApi-mysql
     
  mountainpeakapi-container:
      image:  mountainpeakapi
      networks:
      - mountainPeakApi-mysql
      build: ./
      ports:
        - "8081:8081"
      depends_on:
        - peakdb
networks:
  mountainPeakApi-mysql: